apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ray
  name: autoscaler
subjects:
- kind: ServiceAccount
  namespace: ray
  name: autoscaler
roleRef:
  kind: Role
  name: autoscaler
  apiGroup: rbac.authorization.k8s.io
