kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ray
  name: autoscaler
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete", "patch"]
