apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  namespace: ray
spec:
  restartPolicy: Never
  #affinity:
  #podAntiAffinity:
  #requiredDuringSchedulingIgnoredDuringExecution:
  #- labelSelector:
  #matchLabels:
  #type: ray
  #topologyKey: kubernetes.io/hostname
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
    - name: ray-head
      image: eoakes/ray-test
      imagePullPolicy: IfNotPresent # TODO
      command: [ "/bin/bash", "-c", "--" ]
      args: ["ray start --head --redis-port=6379 --redis-shard-ports=6380,6381 --object-manager-port=12345 --node-manager-port=12346 --node-ip-address=$MY_POD_IP --block"]
      ports:
        - containerPort: 6379
        - containerPort: 6380
        - containerPort: 6381
        - containerPort: 12345
        - containerPort: 12346
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      env:
        - name: LC_ALL
          value: "C.UTF-8"
        - name: LANG
          value: "C.UTF-8"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      resources:
        limits:
          cpu: 500m
          memory: 2.5Gi
