apiVersion: v1
kind: Pod
metadata:
  namespace: ray
  generateName: ray-worker-
spec:
  restartPolicy: Never
  affinity:
    #podAntiAffinity:
    #requiredDuringSchedulingIgnoredDuringExecution:
    #- labelSelector:
    #matchLabels:
    #type: ray
    #topologyKey: kubernetes.io/hostname
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: ray-worker
    image: eoakes/ray-test
    command: ["/bin/bash", "-c", "--"]
    args: ["ray start --node-ip-address=$MY_POD_IP --redis-address=$RAY_HEAD_SERVICE_HOST:$RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY --object-manager-port=12345 --node-manager-port=12346 --block"]
    ports:
      - containerPort: 12345
      - containerPort: 12346
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    env:
      - name: LC_ALL
        value: "C.UTF-8"
      - name: LANG
        value: "C.UTF-8"
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MY_CPU_LIMIT
        valueFrom:
          resourceFieldRef:
            containerName: ray-worker
            resource: limits.cpu
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
