apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-worker
  namespace: ray
spec:
  replicas: 2
  selector:
    matchLabels:
      component: ray-worker
      type: ray
  template:
    metadata:
      labels:
        component: ray-worker
        type: ray
    spec:
      restartPolicy: Always
      affinity:
        #podAntiAffinity:
        #requiredDuringSchedulingIgnoredDuringExecution:
        #- labelSelector:
        #matchLabels:
        #type: ray
        #topologyKey: kubernetes.io/hostname
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: ray-worker
        image: eoakes/ray-test
        command: ["/bin/bash", "-c", "--"]
        args: ["ray start --node-ip-address=$MY_POD_IP --redis-address=$RAY_HEAD_SERVICE_HOST:$RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY --object-manager-port=12345 --node-manager-port=12346 --block"]
        ports:
          - containerPort: 12345
          - containerPort: 12346
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: ray-worker
                resource: limits.cpu
          - name: MY_MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: ray-worker
                resource: limits.memory
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
